<!DOCTYPE HTML>
<html lang="es-ES">
<head>
	<meta charset="UTF-8">
	<title>librePOS - Lightweight Point of Sale</title>
	<link rel="shortcut icon" href="<?php echo$s['r']; ?>img/favicon.png" type="image/png" />
	<script type="text/javascript" src="<?php echo$s['r']; ?>js/jquery.js"></script>
	<script type="text/javascript" src="<?php echo$s['r']; ?>js/common.djs"></script>
	<link rel="stylesheet" href="<?php echo$s['r']; ?>css/common.dcss" />
