<?php
include("html/common/header.phtml");
?>
<nav id="management">
<ul id="humanres">
	<span>Recursos humanos</span>
	<li id="clients">Clientes</li>
	<li id="distributors">Distribuidores</li>
</ul>
<ul id="store">
	<span>Almacén</span>
	<li id="products">Productos</li>
	<li id="makes">Marcas</li>
	<li id="categories">Categorías</li>
	<li id="discounts">Descuentos</li>
	<li id="purchase">Compras</li>
</ul>
<ul id="informs">
	<span>Informes</span>
	<li id="i_sales">Ventas</li>
	<li id="i_stock">Existencias</li>
	<li id="i_clients">Clientes</li>
</ul>
</nav>
<div id="panel">
	Elije un menú de la izquierda
</div>
