<header id="topbar">
	<a href="<?php echo$s['r']; ?>" id="logo"><img src="<?php echo$s['r']; ?>img/logo.png" alt="librePOS" /></a>
	<nav>
		<ul>
			<li><a href="<?php echo$s['r']; ?>sale" id="navsale">VENTAS</a></li>
			<li><a href="<?php echo$s['r']; ?>management" id="navmanagement">GESTIÓN</a></li>
			<li><a href="<?php echo$s['r']; ?>system" id="navsystem">SISTEMA</a></li>
		</ul>
	</nav>
	<div id="context">
		<?php include("html/".$mod."/context.phtml"); ?>
	</div>
	<a href="<?php echo$s['r']; ?>session/exit" id="exit">Salir <img src="<?php echo$s['r']; ?>img/icons/exit.png" alt="→" /></a>
	<div id="session">
		<span id="clock"></span>
		<br />
		<span id="user"></span>
	</div>
</header>
